---
title: "Regional Share Analysis"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, echo = FALSE, warning = FALSE)

require(tidyverse)
require(sf)
require(areal)
require(ggplot2)
require(rpgcolorsr)
require(gridExtra)
require(kableExtra)
require(ggrepel)
require(tmap)
require(rmapshaper)
library(scales)

options(scipen = 999)

#devtools::install_github("BFroebRPG/rpgcolorsr")

```

```{r read in data}

zones_land <- readRDS("K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\zones_land.rds")

corridor <- readRDS("K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\corridor.rds")

station_buffers <- readRDS("K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\station_buffers.rds")

station_points <- readRDS("K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\station_points.rds")

corridor_buffer_half <- readRDS("K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\corridor_buffer_half.rds")

tod_scenario <- readRDS("K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\tod_scenario.rds")

station_buffers_no_overlap <- readRDS("K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\station_buffers_no_overlap.rds")

#corridor_parcels <- readRDS("K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\corridor_parcels.rds")

corridor_area_weighted_combined <- readRDS("K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\area_weighted_corridor_combined.rds")

```

The following charts reveal the distribution of forecasted dwelling unit and employment growth occurring inside and outside the corridor by both land use scenarios. They reveal the increase in regional growth the corridor would need to absorb.


```{r calculate growth for each category}

area_weighted_summary_wider <- corridor_area_weighted_combined %>% pivot_wider(names_from = year, values_from = count, names_prefix = "yr_") %>% 
  mutate(growth = yr_2045-yr_2020)

```



```{r}

gg_emp_growth <- ggplot(data=filter(area_weighted_summary_wider, type == "emp"), aes(x=scenario, y=growth, fill=area)) +
  geom_bar(stat="identity") +
  scale_fill_rpg(palette = "rpg_colors") +
  xlab("") +
  ylab("Employment Growth") +
  ggtitle("Job Growth by Scenario") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10))


gg_du_growth <- ggplot(data=filter(area_weighted_summary_wider, type == "du"), aes(x=scenario, y=growth, fill=area)) +
  geom_bar(stat="identity") +
  scale_fill_rpg(palette = "rpg_colors") +
  xlab("") +
  ylab("Dwelling Unit Growth") +
  ggtitle("Dwelling Unit Growth by Scenario") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10))


grid.arrange(gg_emp_growth, gg_du_growth, ncol=2)


```
