---
title: "Lakeland TOD Target Analysis"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
require(sf)
require(areal)
require(ggplot2)
require(rpgcolorsr)
require(gridExtra)
require(kableExtra)
require(ggrepel)
require(tmap)
require(rmapshaper)
library(scales)

options(scipen = 999)

#devtools::install_github("BFroebRPG/rpgcolorsr")

```


```{r buffer without overlap}

# code adapted from https://github.com/r-spatial/sf/issues/824

st_buffer_without_overlap <- function(centroids, dist) {

     # Voronoi tesselation
     voronoi <- 
          centroids %>% 
          st_geometry() %>%
          st_union() %>%
          st_voronoi() %>%
          st_collection_extract()
     
     # Put them back in their original order
     voronoi <-
          voronoi[unlist(st_intersects(centroids,voronoi))]

     # Keep the attributes
     result <- centroids
     
     # Intersect voronoi zones with buffer zones
     st_geometry(result) <-
          mapply(function(x,y) st_intersection(x,y),
                 st_buffer(st_geometry(centroids),dist), 
                 voronoi,
                 SIMPLIFY=FALSE) %>%
          st_sfc(crs=st_crs(centroids))

     result
}

```


```{r read in data}

#set projection variable to Virginia state plane
crs <- 2237

#read in zone data Shapefile
zones <- st_read("K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\Model\\tpo_2045_forecast\\2045 Forecast\\Polk_SE_Forecast_2045.shp") %>% st_transform(crs) %>% 
  st_make_valid()

#read in station points Shapefile
station_points <- st_read("K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\lakeland_proposed_stations_v3.shp") %>% st_transform(crs)

parcels <- st_read("K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\Parcles_2019\\Parcels_2019_StudyArea_wAttributes.shp") %>% 
  st_transform(crs) %>% 
  st_make_valid()

corridor <- st_read("K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\study_corridor_v3.shp") %>% 
  st_transform(crs)

#buffer station points
station_buffers <- st_buffer(station_points, 
                             2640) 


station_buffers_no_overlap <- st_buffer_without_overlap(station_points, 
                             2640)

corridor_buffer_half <- st_buffer(corridor, 
                             2640)

corridor_buffer_mile <- st_buffer(corridor, 
                             5280)

landuse <- st_read("K:\\Projects\\Florida\\Features\\LU\\StateWideLU_FDEP\\StateWideLU.gdb", "StatewideLU")

landuse_water <- landuse %>% 
  filter(LEVEL1_LANDUSE_DESCRIPTION == "Water") %>% 
  st_filter(., zones, .predicate = st_intersects) %>% 
  select() %>% 
  st_make_valid()


```

```{r add density to zones}

#any(is.na(st_dimension(zones)))
#any(is.na(st_is_valid(zones)))

zones_land <- st_difference(zones, st_union(landuse_water)) 

zones_land$geometry[175] <- st_collection_extract(zones_land$geometry[175], "POLYGON") %>% 
  st_combine %>% 
  st_cast(.,"MULTIPOLYGON")
```

```{r select parcels that intersect with corridor}

corridor_parcels <- st_filter(parcels, corridor_buffer_half, .predicate = st_intersects)

```


```{r}

landuse_corridor <- st_filter(landuse, corridor_buffer_half, .predicate = st_intersects)

landuse_corridor <- st_make_valid(landuse_corridor)

tm_shape(corridor_buffer_half) + tm_borders() +
tm_shape(zones_land) + tm_polygons()

```


```{r write data}

write_rds(zones_land, "K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\zones_land.rds")

write_rds(corridor, "K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\corridor.rds")

write_rds(station_buffers, "K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\station_buffers.rds")

write_rds(station_points, "K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\station_points.rds")

write_rds(corridor_buffer_half, "K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\corridor_buffer_half.rds")

write_rds(corridor_parcels, "K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\corridor_parcels.rds")

write_rds(landuse_corridor, "K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\landuse_corridor.rds")

write_rds(station_buffers_no_overlap, "K:\\Projects\\D1\\Features\\Lakeland_AAA_Phase3\\US98\\TOD_Land_Use_Analysis\\station_buffers_no_overlap.rds")

```
